### PR TITLE
Geo packages + reboot

### PR DESCRIPTION
**Pull request by Stephen-Gates**
This PR adds 

- examples to support the [Point location data in CSV files](https://frictionlessdata.io/guides/point-location-data/) guide
- an improved goodtables.yml file to help contributors test individual data packages

Currently [goodtables.io tests](http://goodtables.io/github/Stephen-Gates/example-data-packages) report an error on the `required` constraint in geopoint-object/data/office-locations.csv. I can't understand this error as there are values in every cell in the column.

[goodtables.io](https://goodtables.io/github/Stephen-Gates/example-data-packages)

Examples 5..7 to follow

### CODE REVIEW

**Comment by roll** [comment]
@Stephen-Gates 
It's great!

I've create an issue for the validation error - https://github.com/frictionlessdata/goodtables-py/issues/244 (it's a bug)

**Comment by Stephen-Gates** [comment]
@roll @rufuspollock I think this is good to go. Badge will fail until frictionlessdata/goodtables-py#244 is fixed.

- Big update to readme. 
- need an approach for dealing with out-of-date packages that are linked to from Guides. Suggestions given there's meant to be a push on Guides?

**Comment by rufuspollock** [comment]
@Stephen-Gates can you open an issue about out of date guides (either here or on website issue tracker).

**Comment by Stephen-Gates** [comment]
@rufuspollock It's already there https://github.com/frictionlessdata/website/issues/152

**Pull request merged**
